export const allFlowerColors = [
  { name: "Black", hex: "#000000", text: "#ffffff" },
  { name: "Blue", hex: "#3279f7", text: "#ffffff" },
  { name: "Blush", hex: "#f48f99", text: "#000000" },
  { name: "Cloud", hex: "#86ecfc", text: "#000000" },
  { name: "Cool Pink", hex: "#e099da", text: "#000000" },
  { name: "Coral", hex: "#ec5b65", text: "#000000" },
  { name: "Cream", hex: "#ffeab2", text: "#000000" },
  { name: "Gray", hex: "#535652", text: "#ffffff" },
  { name: "Green", hex: "#35b04f", text: "#000000" },
  { name: "Hot Pink", hex: "#d9569d", text: "#000000" },
  { name: "Ice", hex: "#86b3ee", text: "#000000" },
  { name: "Gray", hex: "#535652", text: "#ffffff" },
  { name: "Indigo", hex: "#4049ef", text: "#000000" },
  { name: "Lilac", hex: "#be7cf9", text: "#000000" },
  { name: "Lime", hex: "#b7f832", text: "#000000" },
  { name: "Gray", hex: "#535652", text: "#ffffff" },
  { name: "Magenta", hex: "#c03bcc", text: "#000000" },
  { name: "Mint", hex: "#91fb9d", text: "#000000" },
  { name: "Orange", hex: "#f3a01c", text: "#000000" },
  { name: "Peach", hex: "#f8c088", text: "#000000" },
  { name: "Periwinkle", hex: "#a9a2fa", text: "#000000" },
  { name: "Pink", hex: "#ee94c7", text: "#000000" },
  { name: "Pistachio", hex: "#dbfa96", text: "#000000" },
  { name: "Red", hex: "#c12a3d", text: "#000000" },
  { name: "Seafoam", hex: "#85f4d6", text: "#000000" },
  { name: "Sky", hex: "#1cb3fa", text: "#000000" },
  { name: "Teal", hex: "#47c6c0", text: "#000000" },
  { name: "Gray", hex: "#535652", text: "#ffffff" },
  { name: "Violet", hex: "#6545c3", text: "#000000" },
  { name: "Warm Pink", hex: "#ffb7cb", text: "#000000" },
  { name: "White", hex: "#eae4e7", text: "#000000" },
  { name: "Yellow", hex: "#e8dc47", text: "#000000" },
];

export const flowerSpecies = [
  {
    name: "Bellbutton",
    code: "BL",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Gemstone",
      "Greenhouse",
      "Cloud",
      "Wheatflower",
    ],
  },
  {
    name: "Dandelily",
    code: "DL",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Gemstone",
      "Greenhouse",
      "Cloud",
      "Wheatflower",
    ],
  },
  {
    name: "Pestemum",
    code: "PM",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Gemstone",
      "Greenhouse",
      "Cloud",
      "Wheatflower",
    ],
  },
  {
    name: "Tulias",
    code: "TL",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Gemstone",
      "Greenhouse",
      "Cloud",
      "Wheatflower",
    ],
  },
  {
    name: "Hibiscus",
    code: "HB",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Volcano",
      "Greenhouse",
      "Wheatflower",
    ],
  },
  {
    name: "Ghostgleam",
    code: "GG",
    biomes: ["Swamp", "Gemstone", "Reef", "Greenhouse", "Cloud", "Wheatflower"],
  },
  {
    name: "Thistle",
    code: "TH",
    biomes: ["Swamp", "Gemstone", "Volcano", "Greenhouse", "Wheatflower"],
  },
  {
    name: "Heavy Nettle",
    code: "HN",
    biomes: ["Gemstone", "Volcano", "Greenhouse", "Wheatflower"],
  },
  {
    name: "Anemone",
    code: "AN",
    biomes: ["Reef", "Greenhouse", "Cloud", "Wheatflower"],
  },
  {
    name: "Dreampuff",
    code: "DP",
    biomes: ["Greenhouse", "Cloud", "Wheatflower"],
  },
  { name: "Frostfeather", code: "FF", biomes: ["Peak"] },
  { name: "Blazebulb", code: "BZ", biomes: ["Caldera"] },
  { name: "Crystalia", code: "CY", biomes: ["Caves"] },
  { name: "Bubbaluna", code: "BU", biomes: ["Moon"] },
  {
    name: "Wheatflower",
    code: "WF",
    biomes: ["Greenhouse", "Wheatflower"],
  },
  {
    name: "Marigold",
    code: "MG",
    biomes: [
      "Meadow",
      "Resort",
      "Gemstone",
      "Volcano",
      "Greenhouse",
      "Wheatflower",
    ],
  },
  {
    name: "Eggwort",
    code: "EG",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Gemstone",
      "Volcano",
      "Reef",
      "Greenhouse",
      "Cloud",
      "Peak",
      "Caldera",
      "Caves",
      "Moon",
      "Wheatflower",
    ],
  },
  {
    name: "Pinwheel",
    code: "PW",
    biomes: [
      "Meadow",
      "Resort",
      "Gemstone",
      "Greenhouse",
      "Cloud",
      "Wheatflower",
    ],
  },
  {
    name: "Petunia",
    code: "PT",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Gemstone",
      "Greenhouse",
      "Wheatflower",
    ],
  },
  {
    name: "Bowblossom",
    code: "BB",
    biomes: [
      "Meadow",
      "Resort",
      "Reef",
      "Greenhouse",
      "Cloud",
      "Peak",
      "Caldera",
      "Caves",
      "Wheatflower",
    ],
  },
  {
    name: "Poinsettia",
    code: "PS",
    biomes: ["Meadow", "Resort", "Swamp", "Greenhouse", "Wheatflower"],
  },
  {
    name: "Glowbal",
    code: "GB",
    biomes: [
      "Meadow",
      "Resort",
      "Swamp",
      "Greenhouse",
      "Cloud",
      "Peak",
      "Caldera",
      "Caves",
      "Wheatflower",
      "Moon",
    ],
  },
  {
    name: "Rose",
    code: "RS",
    biomes: ["Meadow", "Resort", "Greenhouse", "Wheatflower"],
  },
  {
    name: "Happadil",
    code: "HP",
    biomes: [
      "Meadow",
      "Resort",
      "Gemstone",
      "Volcano",
      "Greenhouse",
      "Cloud",
      "Caves",
      "Wheatflower",
      "Moon",
    ],
  },
];

export const flowerPatterns = [
  "Ombré",
  "Glitter",
  "Frost",
  "Molten",
  "Crystal",
  "Cosmic",
  "Trim",
  "Speckled",
  "Alternate",
  "Striped",
  "Patch",
  "Ring",
  "Confetti",
  "Iridescent",
  "Glow",
];
